ghg/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.template_inicio, name='ghg_inicio'),  # compras
    path('import', views.template_import, name='ghg_import'),
    path('dataini', views.dataini, name='ghg_dataini'),
]

morfee_frontier/urls.py
# from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
from . import views

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(template_name='morfee_frontier/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password_change/', views.CustomChangePWDView.as_view(template_name='users/password_change_form.html'), name='password_change'),
    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),

    path('', views.inicio, name='inicio'),
    path('diccionario', views.diccionario, name='ad_diccionario'),
    # path('clientes', views.clientes, name='ad_clientes_vue'),
    # path('modulos', views.modulos, name='ad_modulos_vue'),
    path('diccionario/build', views.infoForDictio, name='ad_info_dictio'),
    path('diccionario/collections', views.getCollections, name='ad_collections'),
    path('diccionario/collection', views.getCollection, name='ad_collection'),
    path('diccionario/update', views.updateField, name='ad_dictio_edit'),
    path('diccionario/cliente', views.dicsOfUser, name='ad_dictio_client'),
    path('users/', include('users.urls')),
    path('aseguramiento/', include('aseguramiento.urls')),
    path('vacunacion/', include('vacunacion.urls')),
    path('reservas/', include('reservas.urls')),
    path('auditorias/', include('auditorias.urls')),
    path('financiero/', include('financiero.urls')),
    path('servicios/', include('servicios.urls')),
    path('ghg/', include('ghg.urls')),
    path('inte_', views.inicio, name='inte_inicio'),
]# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('admin/users', views.user_list, name='ad_user_list'),
    path('admin/user/select', views.user_preselect, name='ad_user_preselect'),
    path('admin/user/add', views.user_add, name='ad_user_add'),
    path('admin/user/add/staff', views.user_add_staff, name='ad_user_add_staff'),
    path('admin/user/edit/<int:id>/', views.user_edit, name='ad_user_edit'),
    path('admin/user/remove/<int:id>/', views.user_remove, name='ad_user_remove'),
    path('list', views.cli_user_list, name='ad_ucli_list'),
    path('add', views.cli_user_add, name='ad_ucli_add'),
    path('store', views.cli_user_add, name='ad_ucli_store'),
    path('edit/<int:id>/', views.cli_user_edit, name='ad_ucli_edit'),

    path('admin/clientes', views.cliente_list, name='ad_cliente_list'),
    path('admin/cliente/add', views.cliente_add, name='ad_cliente_add'),
    path('admin/cliente/edit/<int:id>/', views.cliente_edit, name='ad_cliente_edit'),
    path('admin/roles', views.rol_list, name='ad_rol_list'),
    path('admin/rol/add', views.rol_add, name='ad_rol_add'),
    path('admin/rol/edit/<int:id>/', views.rol_edit, name='ad_rol_edit'),
    path('admin/rol/remove/<int:id>/', views.rol_remove, name='ad_rol_remove'),
    path('admin/modulos', views.modulo_list, name='ad_modulo_list'),
    path('admin/modulo/add', views.modulo_add, name='ad_modulo_add'),
    path('admin/modulo/edit/<int:id>/', views.modulo_edit, name='ad_modulo_edit'),
    path('admin/modulo/remove/<int:id>/', views.modulo_remove, name='ad_modulo_remove'),
    path('admin/diccionario/<str:coleccion>/', views.get_diccionario, name="ad_diccionario"),
    path('admin/basic/import', views.basic_import_add, name='ad_basic_import'),
    path('admin/history/import', views.import_history, name='ad_history_import'),
    path('admin/basic/import/remove', views.import_delete_basic, name='ad_remove_import'),
    path('admin/reader', views.auto_reader_colection, name='ad_auto_reader'),
    path('admin/last/import', views.getLastImport, name='ad_last_import'),

    path('admin/codigo/import', views.getImport, name='ad_code_import'),
    path('ismael', views.ismael, name='ad_ismael'),
]

users/models.py
from unittest.util import _MAX_LENGTH
from bson.json_util import default
from django.db import models
from django.contrib.auth.models import AbstractUser

class AuthCliente(models.Model):
    cliente = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    correo = models.CharField(max_length=100)
    contacto = models.CharField(max_length=30)
    modulos = models.CharField(max_length=100, blank=True)
    is_indigena = models.BooleanField()

    class Meta:
        db_table = 'auth_cliente'

    @property
    def badges(self):
        return self.modulos.split("|")

    @property
    def sp(self):
        return 'Salud Pública'

    @property
    def modulos_to_dict(self):
        return dict.fromkeys(self.modulos.split("|"), True)

    def __str__(self):
        return self.cliente

class AuthModulo(models.Model):
    modulo = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=250, blank=True, null=True)
    clave = models.CharField(max_length=10)
    estado = models.CharField(max_length=20)

    class Meta:
        db_table = 'auth_modulo'

    def __str__(self):
        return self.modulo

class AuthRol(models.Model):
    rol = models.CharField(max_length=20)
    nivel = models.IntegerField()

    class Meta:
        db_table = 'auth_rol'

    def __str__(self):
        return self.rol

class UserMorfee(AbstractUser):
    cliente = models.ForeignKey(AuthCliente, models.SET_NULL, blank=True, null=True)
    rol = models.ForeignKey(AuthRol, models.SET_NULL, blank=True, null=True)

class Diccionario(models.Model):
    class DataOptions(models.TextChoices):
        MORFEE = 'Morfee'
        CLIENTE = 'Cliente'

    class TypeHeadOptions(models.TextChoices):
        AUTO = 'auto'
        FILE_PARSE = 'file_parse'
        FILE_FIXED = 'file_fixed'
        FILE_FREE = 'file_free'

    modulo = models.CharField(max_length=30)
    coleccion = models.CharField(max_length=50, unique=True)
    alias = models.CharField(max_length=50)
    campos = models.CharField(max_length=700)
    has_data = models.IntegerField(default=0)
    type_head = models.CharField(max_length=10, choices=TypeHeadOptions.choices, default=TypeHeadOptions.FILE_FREE)
    propietario = models.CharField(max_length=10, choices=DataOptions.choices, default=DataOptions.CLIENTE)
    cliente = models.ForeignKey(AuthCliente, models.SET_NULL, blank=True, null=True)
    reglas = models.CharField(max_length=200, blank=True, default='')
    tipo = models.CharField(max_length=10, default='final')

    class Meta:
        db_table = 'diccionario'

class ControlImportBasic(models.Model):
    campos = models.CharField(max_length=500, null=True)
    cliente = models.ForeignKey(AuthCliente, models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(UserMorfee, models.SET_NULL, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    coleccion = models.CharField(max_length=50, blank=True, default='')
    total = models.IntegerField(default=0)
    clave = models.CharField(max_length=20, null=True)
    estado = models.CharField(max_length=10, null=True)

    class Meta:
        db_table = 'control_import_basic'

    @property
    def created_str(self):
        return self.created_at.strftime("%Y-%m-%d")

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from morfee_frontier.mongo import Mongo
import pandas as pd
import json, datetime
from . import forms, models
from django.db import connection

# SECTION USERS
@login_required(login_url='/login/')
def user_list(request):
    datos = models.UserMorfee.objects.all()
    return render(request, 'users/user_list.html', {'datos': datos})

@login_required(login_url='/login/')
def user_preselect(request):
    return render(request, 'users/user_preselect.html')

@login_required(login_url='/login/')
def user_add(request):
    if request.method == "POST":
        form = forms.UserMorfeeForm(request.POST)
        if form.is_valid():
            user = models.UserMorfee()
            user.username = request.POST.get('username')
            user.set_password(request.POST.get('password1'))
            user.first_name = request.POST.get('first_name')
            user.last_name = request.POST.get('last_name')
            user.email = request.POST.get('email')
            user.cliente = models.AuthCliente.objects.get(pk=request.POST.get('cliente'))
            user.rol = models.AuthRol.objects.get(pk=request.POST.get('rol'))
            user.save()
            return redirect('ad_user_list')
        else:
            return render(request, 'users/user_add.html', {'form': form})
    else:
        return render(request, 'users/user_add.html', {'form': forms.UserMorfeeForm()})

@login_required(login_url='/login/')
def user_add_staff(request):
    if request.method == "POST":
        form = forms.UserStaffForm(request.POST)
        if form.is_valid():
            user = models.UserMorfee()
            user.username = request.POST.get('username')
            user.set_password(request.POST.get('password1'))
            user.first_name = request.POST.get('first_name')
            user.last_name = request.POST.get('last_name')
            user.email = request.POST.get('email')
            user.is_staff = True
            user.save()
            return redirect('ad_user_list')
        else:
            return render(request, 'users/user_add_staff.html', {'form': form})
    else:
        return render(request, 'users/user_add_staff.html', {'form': forms.UserStaffForm()})

@login_required(login_url='/login/')
def user_edit(request, id):
    try:
        user = models.UserMorfee.objects.get(pk=id)
        plantilla = 'users/user_edit_staff.html' if user.is_superuser or user.is_staff else 'users/user_edit.html'
        if request.method == "POST":
            form = forms.UserEditStaffForm(request.POST, instance=user) if user.is_superuser or user.is_staff else forms.UserEditForm(request.POST, instance=user)
            if form.is_valid():
                form.save()
                return redirect('ad_user_list')
            else:
                return render(request, plantilla, {'form': form, 'usuario': user})
        else:
            form = forms.UserEditStaffForm(instance=user) if user.is_superuser or user.is_staff else forms.UserEditForm(instance=user)
            return render(request, plantilla, {'form': form, 'usuario': user})
    except models.UserMorfee.DoesNotExist:
        return render(request, 'users/not_found.html', {'mensaje': 'No se pudo encontrar el registro solicitado, por favor consulte con el administrador del sitio.'})

@login_required(login_url='/login/')
def user_remove(request, id):
    try:
        user = models.UserMorfee.objects.get(pk=id)
        if not user.is_superuser:
            try:
                user.delete()
                return redirect('ad_user_list')
            except models.UserMorfee.DoesNotExist:
                return render(request, 'morfeeweb/not_found.html', {'titulo': 'Mi titulo', 'mensaje': 'No se pudo encontrar el registro solicitado, por lo tanto, no se puede eliminar, por favor consulte con el administrador del sitio.'})
        else:
            return redirect('ad_user_list')
    except models.UserMorfee.DoesNotExist:
        return render(request, 'users/not_found.html', {'mensaje': 'No se pudo encontrar el registro solicitado, por favor consulte con el administrador del sitio.'})


# SECTION CLIENTES
@login_required(login_url='/login/')
def cli_user_list(request):
    uid = request.user.cliente_id
    datos = models.UserMorfee.objects.filter(cliente_id=uid)
    return render(request, 'users/cli_user_list.html', {'datos': datos})

@login_required(login_url='/login/')
def cli_user_add(request):
    if request.method == "POST":
        form = forms.UserMorfeeForm(request.POST)
        if form.is_valid():
            user = models.UserMorfee()
            user.username = request.POST.get('username')
            user.set_password(request.POST.get('password1'))
            user.first_name = request.POST.get('first_name')
            user.last_name = request.POST.get('last_name')
            user.email = request.POST.get('email')
            user.cliente = models.AuthCliente.objects.get(pk=request.POST.get('cliente'))
            user.rol = models.AuthRol.objects.get(pk=request.POST.get('rol'))
            user.save()
            return redirect('ad_ucli_list')
        else:
            return render(request, 'users/cli_user_add.html', {'form': form})
    else:
        return render(request, 'users/cli_user_add.html', {'form': forms.UserClientForm(request.user.cliente_id)})

@login_required(login_url='/login/')
def cli_user_edit(request, id):
    try:
        user = models.UserMorfee.objects.get(pk=id)
        if request.method == "POST":
            form = forms.UserEditStaffForm(request.POST, instance=user) if user.is_superuser or user.is_staff else forms.UserEditForm(request.POST, instance=user)
            if form.is_valid():
                form.save()
                return redirect('ad_ucli_list')
            else:
                return render(request, 'users/cli_user_edit.html', {'form': form, 'usuario': user})
        else:
            # form = forms.UserClientEditForm(instance=user)
            form = forms.UserClientEditForm(instance=user, daky=request.user.cliente_id)
            return render(request, 'users/cli_user_edit.html', {'form': form, 'usuario': user})
    except models.UserMorfee.DoesNotExist:
        return render(request, 'users/not_found.html', {'mensaje': 'No se pudo encontrar el registro solicitado, por favor consulte con el administrador del sitio.'})

@login_required(login_url='/login/')
def cli_user_store(request):
    if request.method == "POST":
        form = forms.UserMorfeeForm(request.POST)
        if form.is_valid():
            user = models.UserMorfee()
            user.username = request.POST.get('username')
            user.set_password(request.POST.get('password1'))
            user.first_name = request.POST.get('first_name')
            user.last_name = request.POST.get('last_name')
            user.email = request.POST.get('email')
            user.cliente = models.AuthCliente.objects.get(pk=request.POST.get('cliente'))
            user.rol = models.AuthRol.objects.get(pk=request.POST.get('rol'))
            user.save()
            return redirect('ad_user_list')
        else:
            return render(request, 'users/user_add.html', {'form': form})
    else:
        return render(request, 'users/user_add.html', {'form': forms.UserMorfeeForm()})

@login_required(login_url='/login/')
def changeLock(request):
    return render(request, 'users/change_lock.html')

@login_required(login_url='/login/')
def cliente_list(request):
    datos = models.AuthCliente.objects.all()
    return render(request, 'users/cliente_list.html', {'datos': datos})

@login_required(login_url='/login/')
def cliente_add(request):
    if request.method == "POST":
        form = forms.ClienteForm(request.POST)
        if form.is_valid():
            cli = models.AuthCliente()
            cli.cliente = request.POST.get('cliente')
            cli.direccion = request.POST.get('direccion')
            cli.correo = request.POST.get('correo')
            cli.contacto = request.POST.get('contacto')
            cli.modulos = "|".join(request.POST.getlist('modulos'))
            cli.is_indigena = 1 if request.POST.get('is_indigena') else None
            cli.save()
            diccionarios = models.Diccionario.objects.filter(tipo='template')
            for dc in diccionarios:
                n_dic = models.Diccionario()
                n_dic.modulo = dc.modulo
                n_dic.coleccion = dc.coleccion + str(cli.id)
                n_dic.alias = dc.alias
                n_dic.campos = dc.campos
                n_dic.has_data = 0
                n_dic.type_head = dc.type_head
                n_dic.propietario = dc.propietario
                n_dic.cliente = cli
                n_dic.reglas = dc.reglas
                n_dic.tipo = 'final'
                n_dic.save()
            return redirect('ad_cliente_list')
        else:
            return render(request, 'users/cliente_add.html', {'form': form})
    else:
        return render(request, 'users/cliente_add.html', {'form': forms.ClienteForm()})

@login_required(login_url='/login/')
def cliente_edit(request, id):
    try:
        cli = models.AuthCliente.objects.get(pk=id)
        if request.method == "POST":
            form = forms.ClienteForm(request.POST)
            if form.is_valid():
                cli.cliente = request.POST.get('cliente')
                cli.direccion = request.POST.get('direccion')
                cli.correo = request.POST.get('correo')
                cli.contacto = request.POST.get('contacto')
                cli.modulos = "|".join(request.POST.getlist('modulos'))
                cli.is_indigena = 1 if request.POST.get('is_indigena') else None
                cli.save()
                return redirect('ad_cliente_list')
            else:

users/templates/users/a_ismael.html
{% extends "morfee_frontier/base.html" %}
{% load static %}
{% block contenido %}
<div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h5 class="txt-dark">ADMINISTRADOR</h5>
    </div>
    <!-- Breadcrumb -->
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{% url 'inicio' %}">Inicio</a></li>
            <li class="active"><span>Usuarios</span></li>
        </ol>
    </div>
    <!-- /Breadcrumb -->
</div>
<div class="panel panel-default card-view border">
    <div class="panel-heading">
        <h6 class="panel-title fs-5">FINANZAS</h6>
    </div>
    <div class="panel-wrapper collapse in">
        <div class="panel-body">
            <h5>Importar Finanzas Públicas</h5>
            <import-basic 
                destino="1_finan_public" 
                separador_mode="normal" 
                subtitulo="FINANZAS PÚBLICAS ZEN" 
                separador=";" 
                sindiccionario
                head="file_fixed"
                fields="cod|den|eps|val"
                rules="cod:string"
                codec_mode="show"
                error="ignore"
                error_mode="show"
                info
                extra>
            </import-basic>
            <hr>
            <h5>Importar Cuentas</h5>
            <import-basic 
                destino="1_finan_cuentas" 
                separador_mode="normal" 
                subtitulo="TODAS LAS CUENTAS" 
                separador=";" 
                sindiccionario
                head="file_fixed"
                fields="cod|den|len"
                rules="cod:string"
                codec_mode="show"
                error="ignore"
                error_mode="show"
                info
                extra>
            </import-basic>

        </div>
    </div>
</div>
{% endblock %}

users/templates/users/cliente_add.html
{% extends "morfee_frontier/base.html" %}
{% load static %}
{% block contenido %}
<div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h5 class="txt-dark">ADMINISTRADOR</h5>
    </div>
    <!-- Breadcrumb -->
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{% url 'inicio' %}">Inicio</a></li>
            <li><a href="{% url 'ad_cliente_list' %}">Clientes</a></li>
            <li class="active"><span>Registrar</span></li>
        </ol>
    </div>
    <!-- /Breadcrumb -->
</div>
<div class="panel panel-default card-view border">
    <div class="panel-heading border-bottom bg-success">
        <h6 class="panel-title fs-5">REGISTRO DE CLIENTE</h6>
    </div>
    <div class="panel-wrapper collapse in">
        <div class="panel-body pt-4">
            <form action="{% url 'ad_cliente_add' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 border-end">
                        <h6 class="txt-dark"><i class="fa fa-edit me-2"></i> Datos básicos</h6>
                        <hr class="light-grey-hr">
                        <div class="form-group mb-4">
                            {{ form.cliente.label }}
                            {{ form.cliente }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.cliente.errors %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.direccion.label }}
                            {{ form.direccion }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.direccion.errors %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.correo.label }}
                            {{ form.correo }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.correo.errors %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.contacto.label }}
                            {{ form.contacto }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.contacto.errors %}
                        </div>
                        <div class="form-groupx mb-4">
                            <div class="checkbox checkbox-success">
                                {{ form.is_indigena }}
                                <label for="id_is_indigena">{{ form.is_indigena.label }}</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h6 class="txt-dark"><i class="fa fa-cubes me-2"></i> Módulos disponibles</h6>
                        <hr class="light-grey-hr">
                        <div class="mb-2 txt-dark">
                            {{ form.modulos.label }}
                        </div>
                        {% for item in form.modulos %}
                            <div class="form-groupx">
                                <div class="checkbox checkbox-success">
                                    {{ item.tag }}
                                    <label for="{{ item.id_for_label }}">{{ item.choice_label }}</label>
                                </div>
                            </div>
                        {% endfor %}
                        {% include 'morfee_frontier/display_errors.html' with errors=form.modulos.errors %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                    </div>
                </div>
                <hr class="light-grey-hr">
                <div class="text-right">
                    <a href="{% url 'ad_cliente_list' %}" class="btn btn-default"><i class="fa fa-chevron-left"></i> &nbsp;Atrás</a>
                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> &nbsp;Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/cliente_edit.html
{% extends "morfee_frontier/base.html" %}
{% load static %}
{% block contenido %}
<div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h5 class="txt-dark">ADMINISTRADOR</h5>
    </div>
    <!-- Breadcrumb -->
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{% url 'inicio' %}">Inicio</a></li>
            <li><a href="{% url 'ad_cliente_list' %}">Clientes</a></li>
            <li class="active"><span>Editar</span></li>
        </ol>
    </div>
    <!-- /Breadcrumb -->
</div>
<div class="panel panel-default card-view border">
    <div class="panel-heading border-bottom bg-success">
        <h6 class="panel-title fs-5">EDICIÓN DE CLIENTE</h6>
    </div>
    <div class="panel-wrapper collapse in">
        <div class="panel-body pt-4">
            <form action="{% url 'ad_cliente_edit' cliente.id %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 border-end">
                        <h6 class="txt-dark"><i class="fa fa-edit me-2"></i> Datos básicos</h6>
                        <hr class="light-grey-hr">
                        <div class="form-group mb-4">
                            {{ form.cliente.label }}
                            {{ form.cliente }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.cliente.errors %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.direccion.label }}
                            {{ form.direccion }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.direccion.errors %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.correo.label }}
                            {{ form.correo }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.correo.errors %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.contacto.label }}
                            {{ form.contacto }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.contacto.errors %}
                        </div>
                        <div class="form-groupx mb-4">
                            <div class="checkbox checkbox-success">
                                {{ form.is_indigena }}
                                <label for="id_is_indigena">{{ form.is_indigena.label }}</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <h6 class="txt-dark"><i class="fa fa-cubes me-2"></i> Módulos disponibles</h6>
                        <hr class="light-grey-hr">
                        <div class="mb-2 txt-dark">
                            {{ form.modulos.label }}
                        </div>
                        {% for item in form.modulos %}
                            <div class="form-groupx">
                                <div class="checkbox checkbox-success">
                                    {{ item.tag }}
                                    <label for="{{ item.id_for_label }}">{{ item.choice_label }}</label>
                                </div>
                            </div>
                        {% endfor %}
                        {% include 'morfee_frontier/display_errors.html' with errors=form.modulos.errors %}
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                    </div>
                </div>
                <hr class="light-grey-hr">
                <div class="text-right">
                    <a href="{% url 'ad_cliente_list' %}" class="btn btn-default"><i class="fa fa-chevron-left"></i> &nbsp;Atrás</a>
                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> &nbsp;Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/modulo_edit.html
{% extends "morfee_frontier/base.html" %}
{% load static %}
{% block contenido %}
<div class="row heading-bg">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h5 class="txt-dark">ADMINISTRADOR</h5>
    </div>
    <!-- Breadcrumb -->
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{% url 'inicio' %}">Inicio</a></li>
            <li><a href="{% url 'ad_modulo_list' %}">Módulos</a></li>
            <li class="active"><span>Editar</span></li>
        </ol>
    </div>
    <!-- /Breadcrumb -->
</div>
<div class="panel panel-default card-view border">
    <div class="panel-heading border-bottom bg-success">
        <h6 class="panel-title fs-5">EDICIÓN DE MÓDULO</h6>
    </div>
    <div class="panel-wrapper collapse in">
        <div class="panel-body pt-4">
            <form action="{% url 'ad_modulo_edit' modulo.id %}" method="POST">
                {% csrf_token %}
                <div class="d-flex">
                    <div class="flex-fill">
                        <div class="form-group mb-4">
                            {{ form.modulo.label }}
                            {{ form.modulo }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.modulo.errors %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.clave.label }}
                            {{ form.clave }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.clave.errors %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.descripcion.label }}
                            {{ form.descripcion }}
                            {% include 'morfee_frontier/display_errors.html' with errors=form.descripcion.errors %}
                        </div>
                        <div class="form-group mb-4">
                            {{ form.estado.label }}
                            <div class="radio-list mt-2">
                            {% for item in form.estado %}
                                <div class="radio-inline ps-0">
                                    <span class="radio radio-success">
                                        {{ item.tag }}
                                        <label for="{{ item.id_for_label }}">{{ item.choice_label }}</label>
                                    </span>
                                </div>
                            {% endfor %}
                            </div>
                            {% include 'morfee_frontier/display_errors.html' with errors=form.estado.errors %}
                        </div>
                    </div>
                    <div class="px-5">
                        <img src="{% static 'module.png' %}" alt="" height="250">
                    </div>
                </div>
                <hr class="light-grey-hr">
                <div class="text-right">
                    <a href="{% url 'ad_modulo_list' %}" class="btn btn-default"><i class="fa fa-chevron-left"></i> &nbsp;Atrás</a>
                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> &nbsp;Guardar cambios</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}